on:
  push:
    branches: [ "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Tests
        run: nix develop --command pylint ./vaulti

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Tests
        run: nix develop --command mypy ./vaulti
